global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'js-example-app'
    static_configs:
      - targets: ['js-example-app:4000']

  - job_name: 'python-example-app'
    static_configs:
      - targets: ['python-example-app:4001']

  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']
